#!/usr/bin/env python3
import click
import pathlib
import toml


from backends import SUPPORTED_BACKENDS, DEFAULT_CONFIG_PATH, get_backend


@click.group()
def main():
    pass


################################################################################
# Commands for database management
################################################################################
@main.command()
@click.argument('backend', type=click.Choice(SUPPORTED_BACKENDS))
@click.option('-o', '--output', type=click.Path(), default=DEFAULT_CONFIG_PATH,
              show_default=True, help='Destination where to store config')
def config(backend: str, output: pathlib.Path):
    try:
        backend_inst = get_backend(backend)
        with open(output, 'w') as config:
            config.write(backend_inst.Database.config_template)
    except Exception as e:
        print(f'Failed to configure backend \'{backend}\'', e)


@main.command()
@click.option('-F', '--config', type=click.Path(), default=DEFAULT_CONFIG_PATH,
              show_default=True, help='Path to config as source')
def init(config: pathlib.Path):
    try:
        config = toml.load(config)
        backend_type = config.get('BACKEND', None)
        backend_inst = get_backend(backend_type)
        db = backend_inst.Database(config)
        db.init()
    except Exception as e:
        print('Failed to init db', backend_type, e)


@main.command()
@click.option('-F', '--config', type=click.Path(), default=DEFAULT_CONFIG_PATH,
              show_default=True, help='Path to config as source')
def ping(config: pathlib.Path):
    try:
        config = toml.load(config)
        backend_type = config.get('BACKEND', None)
        backend_inst = get_backend(backend_type)
        db = backend_inst.Database(config)
        is_pong = db.ping()
        if not is_pong:
            raise Exception
        print('Pong')
    except Exception as e:
        print('Failed to ping db', backend_type, e)


if __name__ == '__main__':
    main()
