name: kernel-track test and publish

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Assemble jar
        run: ./gradlew jar
      - name: Run tests and checks
        run: ./gradlew check
      - name: Publish artifacts (jar)
        uses: actions/upload-artifact@v3
        with:
          name: kernel-track
          path: app/build/libs/kernel_track.jar


